import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.util.List;

public class TaburiStudent extends Rutare {
    public static JPanel studentDetailsPanel = new JPanel();
    public static final JPanel requestDormBooking = new JPanel();
    public static final JPanel bookingListPanel = new JPanel();

    // Student details panel creation
    public static final JTabbedPane studentJTabs = new JTabbedPane();

    public static void create() {
        // Adding tabs to studentDetailsPane
        createStudentsDetails();
        createBookingDetails();
        ListaCazare.create(bookingListPanel);

        studentJTabs.addTab("Detalii Student", studentDetailsPanel);
        studentJTabs.addTab("Cerere de cazare", requestDormBooking);
        studentJTabs.addTab("Lista cereri de cazare", bookingListPanel);

        // Create repartition list table on a Student Account only if it was generated by a Membru Comisie
        if (JRepartiziareLista.checkRepartitionList()) {
            RepartizareCamereLista.create(TaburiComisie.dormRepartitionPanel);
            studentJTabs.addTab("Repartizare", TaburiComisie.dormRepartitionPanel);
        }

        // Add student tabs to home window panel
        homeWindowPanel.add(studentJTabs, BorderLayout.CENTER);
    }

    public static void createBookingDetails() {
        Utilizatori loggedUtilizatori = Depozit.getLoggedUser();

        JDetaliiCazare.getBookingDetails(String.valueOf(loggedUtilizatori.getId()));
        DetaliiCazare detaliiCazare = Depozit.getBookingDetails();
        if(detaliiCazare != null){
            JLabel submitted = new JLabel("Cererea a fost deja trimisa.");
            requestDormBooking.add(submitted);
            return;
        }
        requestDormBooking.setLayout(new GridLayout(9, 2 ,10,10));
        // Creating fields and labels for requestDormBooking panel

        // Coleg Camera dropdown works with a Constructor Class - StudentDetails
        // The displayed information to the user will be "nume", the second element from the array
        List<DetaliiStudent> studentsNameList = JDetaliiStudent.getStudentsName();
        JComboBox<DetaliiStudent> colegCameraDropdown = new JComboBox<>(studentsNameList.toArray(new DetaliiStudent[1]));

        JComboBox<String> anDropdown = new JComboBox<>(new String[]{"1", "2", "3", "4"});
        anDropdown.setSelectedIndex(0); // Sets default selection to AN 1
        JLabel emptyspace1 = new JLabel((""));
        JLabel emptyspace2 = new JLabel((""));
        JLabel medieAnualaLabel = new JLabel("MEDIA ANUALA:");
        JLabel medieAdmitereLabel = new JLabel("MEDIE ADMITERE:");
        JTextField domiciliuField = new JTextField();
        JTextField medieAnualaField = new JTextField();
        JTextField medieAdmitereField = new JTextField();
        JButton createBooking = new JButton("Confirma cererea");

        // Add action listener to dropdown
        anDropdown.addActionListener(ae -> {
            int selectedYear = Integer.parseInt((String) anDropdown.getSelectedItem());
            boolean showEntryGrade = (selectedYear == 1); // Show entryGradeField only for year 1
            medieAdmitereLabel.setVisible(showEntryGrade);
            medieAdmitereField.setVisible(showEntryGrade);
            medieAnualaLabel.setVisible(!showEntryGrade);
            medieAnualaField.setVisible((!showEntryGrade));

            if (showEntryGrade) {
                requestDormBooking.remove(medieAnualaLabel);
                requestDormBooking.remove(medieAnualaField);
                requestDormBooking.remove(emptyspace2);
                requestDormBooking.add(medieAdmitereLabel);
                requestDormBooking.add(medieAdmitereField);
                requestDormBooking.add(emptyspace1);
                requestDormBooking.add(createBooking);
            } else {
                requestDormBooking.remove(medieAdmitereLabel);
                requestDormBooking.remove(medieAdmitereField);
                requestDormBooking.remove(emptyspace1);
                requestDormBooking.add(medieAnualaLabel);
                requestDormBooking.add(medieAnualaField);
                requestDormBooking.add(emptyspace2);
                requestDormBooking.add(createBooking);
            }
            requestDormBooking.revalidate();
            requestDormBooking.repaint();
        });

        // Add everything to the requestDormBooking panel
        requestDormBooking.add(new JLabel("Coleg camera:"));
        requestDormBooking.add(colegCameraDropdown);
        requestDormBooking.add(new JLabel("Domiciliu:"));
        requestDormBooking.add(domiciliuField);
        requestDormBooking.add(new JLabel("AN:"));
        requestDormBooking.add(anDropdown);
        requestDormBooking.add(medieAdmitereLabel);
        requestDormBooking.add(medieAdmitereField);
        requestDormBooking.add(emptyspace1);
        requestDormBooking.add(createBooking);

        createBooking.addActionListener(ae -> {
            // Now, we sent to database the userId of the selected student
            DetaliiStudent studentInfo = (DetaliiStudent) colegCameraDropdown.getSelectedItem();
            String colegCamera = "";
            if (studentInfo != null) {
                colegCamera = studentInfo.getUserId();
            }
            String an = anDropdown.getItemAt(anDropdown.getSelectedIndex());
            String domiciliu = domiciliuField.getText();
            String medieAnuala = medieAnualaField.getText();
            String medieAdmitere = medieAdmitereField.getText();


            // Check if Student Details Exists before sending a booking dorm request
            JDetaliiStudent.getStudentDetails(String.valueOf(loggedUtilizatori.getId()));
            DetaliiStudent detaliiStudent = Depozit.getStudentDetails();
            if (detaliiStudent == null) {
                JOptionPane.showMessageDialog(null, "Te rugam sa completezi mai intai Detalii Student");
                return;
            }

            try {
                JDetaliiCazare.addBookingDetails(loggedUtilizatori.getId(), colegCamera, domiciliu, an, medieAnuala, medieAdmitere);
                TaburiStudent.requestDormBooking.removeAll();
                requestDormBooking.repaint();
                requestDormBooking.revalidate();
                createBookingDetails();
                // Remount Booking List on add(refetch data from database)
                bookingListPanel.removeAll();
                bookingListPanel.repaint();
                bookingListPanel.revalidate();
                ListaCazare.create(bookingListPanel);
                // Remount Repartitin List on add(refetch data from database)
                TaburiComisie.dormRepartitionPanel.removeAll();
                RepartizareCamereLista.create(TaburiComisie.dormRepartitionPanel);

            } catch (SQLException throwables) {
                throwables.printStackTrace();
            }
        });
    }

    public static void createStudentsDetails() {
        Utilizatori loggedUtilizatori = Depozit.getLoggedUser();

        studentDetailsPanel.setLayout(new GridLayout(0, 2, 10, 10));
        JTextField numeField = new JTextField(20);
        JTextField prenumeField = new JTextField(20);
        JTextField facultateField = new JTextField(20);
        JTextField facultateAnField = new JTextField(20);
        JTextField specializareField = new JTextField(20);
        JTextField cnpField = new JTextField(20);
        cnpField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                cnpField.setBorder(new LineBorder(Color.BLACK));
            }
            @Override
            public void focusLost(FocusEvent e) {
            }
        });
        JTextField domiciliuField = new JTextField(20);
        final JComboBox<String> tipDeStudiiDropDown = new JComboBox<>(new String[]{"Cu Taxa", "Fara Taxa"});
        JButton submitStudentDetailsBtn = new JButton("Adauga");

        // Get Student Details from backend if exists and populate data into fields
        JDetaliiStudent.getStudentDetails(String.valueOf(loggedUtilizatori.getId()));
        DetaliiStudent detaliiStudent = Depozit.getStudentDetails();

        // Access StudentDetails in Storage
        if (detaliiStudent != null) {
            numeField.setText(detaliiStudent.getNume());
            prenumeField.setText(detaliiStudent.getPrenume());
            facultateField.setText(detaliiStudent.getFacultate());
            facultateAnField.setText(detaliiStudent.getAnFacultate());
            specializareField.setText(detaliiStudent.getSpecializare());
            cnpField.setText(detaliiStudent.getCNP());
            domiciliuField.setText(detaliiStudent.getDomiciliu());
            tipDeStudiiDropDown.setSelectedItem(detaliiStudent.getTipDeStudii());
            submitStudentDetailsBtn.setText("Editeaza");
        }

        studentDetailsPanel.add(new JLabel("Nume:"));
        studentDetailsPanel.add(numeField);
        studentDetailsPanel.add(new JLabel("Prenume:"));
        studentDetailsPanel.add(prenumeField);
        studentDetailsPanel.add(new JLabel("Facultate:"));
        studentDetailsPanel.add(facultateField);
        studentDetailsPanel.add(new JLabel("An Facultate:"));
        studentDetailsPanel.add(facultateAnField);
        studentDetailsPanel.add(new JLabel("Specializare:"));
        studentDetailsPanel.add(specializareField);
        studentDetailsPanel.add(new JLabel("CNP:"));
        studentDetailsPanel.add(cnpField);
        studentDetailsPanel.add(new JLabel("Domiciliu:"));
        studentDetailsPanel.add(domiciliuField);
        studentDetailsPanel.add(new JLabel("Tip de studii:"));
        studentDetailsPanel.add(tipDeStudiiDropDown);

        JLabel emptySpace = new JLabel("");
        studentDetailsPanel.add(emptySpace);
        studentDetailsPanel.add(submitStudentDetailsBtn);

        // Listen to Submit Student Details Button
        submitStudentDetailsBtn.addActionListener(ae -> {
            String nume = numeField.getText();
            String prenume = prenumeField.getText();
            String facultate = facultateField.getText();
            String anFacultate = facultateAnField.getText();
            String specializare = specializareField.getText();
            String CNP = cnpField.getText();
            String domiciliu = domiciliuField.getText();
            String tipDeStudii = tipDeStudiiDropDown.getItemAt(tipDeStudiiDropDown.getSelectedIndex());

            if(!CNP.matches(Utilitati.cnpRegex)) {
                cnpField.setBorder(new LineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "CNP is invalid!");
                return;
            }

            // Add or Update student details to students_details table in database/backend
            try {
                JDetaliiStudent.addOrUpdateStudentsDetails(loggedUtilizatori.getId(),nume, prenume, facultate, anFacultate, specializare, CNP, domiciliu, tipDeStudii);
                // Alert User if add/update is successful
                String addOrUpdateDialogMessage = submitStudentDetailsBtn.getText().equals("Editeaza") ? "Editare cu succes" : "Adaugare cu succes";
                JOptionPane.showMessageDialog(null, addOrUpdateDialogMessage);
                submitStudentDetailsBtn.setText("Editeaza");

            } catch (SQLException throwables) {
                throwables.printStackTrace();
            }
        });
    }
}
